2022-07-12 17:29:26 ERROR 409 response executing GraphQL.
2022-07-12 17:29:26 ERROR {"errors":[{"message":"Error 1062: Duplicate entry 'uncategorized-210550' for key 'ix_projects_name_entity_id'","path":["upsertSweep"]}],"data":{"upsertSweep":null}}
2022-07-12 17:29:26 ERROR Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 102, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 140, in execute
    return self.client.execute(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 52, in execute
    result = self._get_result(document, *args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/client.py", line 60, in _get_result
    return self.transport.execute(document, *args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/vendor/gql-0.2.0/wandb_gql/transport/requests.py", line 39, in execute
    request.raise_for_status()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/requests/models.py", line 960, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 409 Client Error: Conflict for url: https://api.wandb.ai/graphql

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1915, in upsert_sweep
    raise (e)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1912, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1892, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.UsageError: Error 1062: Duplicate entry 'uncategorized-210550' for key 'ix_projects_name_entity_id'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/cli/cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/cli/cli.py", line 860, in sweep
    config, project=project, entity=entity, obj_id=sweep_obj_id
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/internal.py", line 102, in upsert_sweep
    return self.api.upsert_sweep(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1915, in upsert_sweep
    raise (e)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1912, in upsert_sweep
    check_retry_fn=no_retry_4xx,
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/lib/retry.py", line 118, in __call__
    if not check_retry_fn(e):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 1892, in no_retry_4xx
    raise UsageError(body["errors"][0]["message"])
wandb.errors.CommError: Error 1062: Duplicate entry 'uncategorized-210550' for key 'ix_projects_name_entity_id'

2022-07-12 17:32:46 ERROR Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 581, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
ValueError: Sweep jonnycook/marlgen/755ylyut not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/cli/cli.py", line 96, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/cli/cli.py", line 1210, in agent
    wandb_agent.agent(sweep_id, entity=entity, project=project, count=count)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/wandb_agent.py", line 612, in agent
    count=count,
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/wandb_agent.py", line 548, in run_agent
    agent.run()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/wandb_agent.py", line 181, in run
    sweep_obj = self._api.sweep(self._sweep_id, "{}")
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/internal.py", line 99, in sweep
    return self.api.sweep(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 58, in wrapper
    raise CommError(message, err).with_traceback(sys.exc_info()[2])
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/apis/normalize.py", line 22, in wrapper
    return func(*args, **kwargs)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/wandb/sdk/internal/internal_api.py", line 581, in sweep
    raise ValueError(f"Sweep {entity}/{project}/{sweep} not found")
wandb.errors.CommError: Sweep jonnycook/marlgen/755ylyut not found

2022-07-12 17:33:36 INFO Running runs: []
2022-07-12 17:33:37 INFO Agent received command: run
2022-07-12 17:33:37 INFO Agent starting run with config:
	entropy_coef: 0.02662048563039438
	eps_clip: 0.7664311648037962
	lr: 0.00012106685460111
2022-07-12 17:33:37 INFO About to run command: /usr/bin/env python ppo_learner.py --entropy_coef=0.02662048563039438 --eps_clip=0.7664311648037962 --lr=0.00012106685460111
2022-07-12 17:33:42 INFO Running runs: ['z6f4mrvh']
2022-07-12 17:33:42 INFO Cleaning up finished run: z6f4mrvh
2022-07-12 17:33:42 INFO Agent received command: run
2022-07-12 17:33:42 INFO Agent starting run with config:
	entropy_coef: 0.05172447205356181
	eps_clip: 0.6856782688607505
	lr: 0.0004064725512790526
2022-07-12 17:33:42 INFO About to run command: /usr/bin/env python ppo_learner.py --entropy_coef=0.05172447205356181 --eps_clip=0.6856782688607505 --lr=0.0004064725512790526
2022-07-12 17:34:12 INFO Running runs: []
2022-07-12 17:34:12 INFO Agent received command: run
2022-07-12 17:34:12 INFO Agent starting run with config:
	entropy_coef: 0.07719933612734427
	eps_clip: 0.5501453163961004
	lr: 0.00014496354581027947
2022-07-12 17:34:12 INFO About to run command: /usr/bin/env python ppo_learner.py --entropy_coef=0.07719933612734427 --eps_clip=0.5501453163961004 --lr=0.00014496354581027947
2022-07-12 17:34:17 INFO Running runs: ['vxuupkn7']
2022-07-12 17:34:17 INFO Cleaning up finished run: vxuupkn7
2022-07-12 17:34:18 INFO Agent received command: run
2022-07-12 17:34:18 INFO Agent starting run with config:
	entropy_coef: 0.03459220482168114
	eps_clip: 0.4833494399837799
	lr: 0.0004413196814646024
2022-07-12 17:34:18 INFO About to run command: /usr/bin/env python ppo_learner.py --entropy_coef=0.03459220482168114 --eps_clip=0.4833494399837799 --lr=0.0004413196814646024
2022-07-12 17:34:44 INFO Running runs: []
2022-07-12 17:34:45 INFO Agent received command: run
2022-07-12 17:34:45 INFO Agent starting run with config:
	entropy_coef: 0.052981762792473366
	eps_clip: 0.09270841854759748
	lr: 0.00040240838060047934
2022-07-12 17:34:45 INFO About to run command: /usr/bin/env python src/learners/ppo_learner.py --entropy_coef=0.052981762792473366 --eps_clip=0.09270841854759748 --lr=0.00040240838060047934
2022-07-12 17:35:22 INFO Running runs: []
2022-07-12 17:35:22 INFO Agent received command: run
2022-07-12 17:35:22 INFO Agent starting run with config:
	entropy_coef: 0.09282289873403976
	eps_clip: 0.31991376569251284
	lr: 0.00022391400569222243
2022-07-12 17:35:22 INFO About to run command: /usr/bin/env python src/main.py --entropy_coef=0.09282289873403976 --eps_clip=0.31991376569251284 --lr=0.00022391400569222243
2022-07-12 17:35:27 INFO Running runs: ['93v1ai8p']
2022-07-15 12:15:37 INFO Running runs: []
2022-07-15 12:15:37 INFO Agent received command: run
2022-07-15 12:15:37 INFO Agent starting run with config:
	epsilon_finish: 0.01727496324402878
	hypernet_embed: 24
	hypernet_layers: 1
	lr: 0.0007590258164525464
	mixing_embed_dim: 37
2022-07-15 12:15:37 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.01727496324402878 --hypernet_embed=24 --hypernet_layers=1 --lr=0.0007590258164525464 --mixing_embed_dim=37
2022-07-15 12:15:42 INFO Running runs: ['edrnxep5']
2022-07-15 12:15:53 INFO Cleaning up finished run: edrnxep5
2022-07-15 12:15:54 INFO Agent received command: run
2022-07-15 12:15:54 INFO Agent starting run with config:
	epsilon_finish: 0.04284625294373463
	hypernet_embed: 33
	hypernet_layers: 2
	lr: 0.0002958845844301301
	mixing_embed_dim: 36
2022-07-15 12:15:54 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.04284625294373463 --hypernet_embed=33 --hypernet_layers=2 --lr=0.0002958845844301301 --mixing_embed_dim=36
2022-07-15 12:15:59 INFO Running runs: ['6e91t94k']
2022-07-15 12:16:09 INFO Cleaning up finished run: 6e91t94k
2022-07-15 12:16:10 INFO Agent received command: run
2022-07-15 12:16:10 INFO Agent starting run with config:
	epsilon_finish: 0.08688599157893058
	hypernet_embed: 38
	hypernet_layers: 4
	lr: 0.0009614298055517252
	mixing_embed_dim: 58
2022-07-15 12:16:10 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.08688599157893058 --hypernet_embed=38 --hypernet_layers=4 --lr=0.0009614298055517252 --mixing_embed_dim=58
2022-07-15 12:16:15 INFO Running runs: ['gzqkz97l']
2022-07-15 12:16:26 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2022-07-15 12:16:26 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2022-07-15 12:22:46 INFO Running runs: []
2022-07-15 12:22:46 INFO Agent received command: run
2022-07-15 12:22:46 INFO Agent starting run with config:
	epsilon_finish: 0.06597788911083294
	hypernet_embed: 58
	hypernet_layers: 3
	lr: 0.00015965088122535587
	mixing_embed_dim: 47
2022-07-15 12:22:46 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.06597788911083294 --hypernet_embed=58 --hypernet_layers=3 --lr=0.00015965088122535587 --mixing_embed_dim=47
2022-07-15 12:22:51 INFO Running runs: ['ertsscly']
2022-07-15 12:23:34 INFO Running runs: []
2022-07-15 12:23:34 INFO Agent received command: run
2022-07-15 12:23:34 INFO Agent starting run with config:
	epsilon_finish: 0.0700306256242132
	hypernet_embed: 28
	hypernet_layers: 1
	lr: 0.000500145728379362
	mixing_embed_dim: 53
2022-07-15 12:23:34 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.0700306256242132 --hypernet_embed=28 --hypernet_layers=1 --lr=0.000500145728379362 --mixing_embed_dim=53
2022-07-15 12:23:39 INFO Running runs: ['biu0cg7o']
2022-07-15 12:23:50 INFO Cleaning up finished run: biu0cg7o
2022-07-15 12:23:50 INFO Agent received command: run
2022-07-15 12:23:50 INFO Agent starting run with config:
	epsilon_finish: 0.03390538920133106
	hypernet_embed: 38
	hypernet_layers: 1
	lr: 0.0005544276731981459
	mixing_embed_dim: 54
2022-07-15 12:23:50 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.03390538920133106 --hypernet_embed=38 --hypernet_layers=1 --lr=0.0005544276731981459 --mixing_embed_dim=54
2022-07-15 12:23:55 INFO Running runs: ['xcnadsv3']
2022-07-15 12:24:06 INFO Cleaning up finished run: xcnadsv3
2022-07-15 12:24:06 INFO Agent received command: run
2022-07-15 12:24:06 INFO Agent starting run with config:
	epsilon_finish: 0.017450334763622767
	hypernet_embed: 58
	hypernet_layers: 1
	lr: 0.0009603477177114114
	mixing_embed_dim: 18
2022-07-15 12:24:06 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.017450334763622767 --hypernet_embed=58 --hypernet_layers=1 --lr=0.0009603477177114114 --mixing_embed_dim=18
2022-07-15 12:24:11 INFO Running runs: ['6oql3uyo']
2022-07-15 12:24:22 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2022-07-15 12:24:22 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2022-07-15 12:25:55 INFO Running runs: []
2022-07-15 12:25:56 INFO Agent received command: run
2022-07-15 12:25:56 INFO Agent starting run with config:
	epsilon_finish: 0.07962667847077837
	hypernet_embed: 36
	hypernet_layers: 1
	lr: 0.0002014473656557767
	mixing_embed_dim: 39
2022-07-15 12:25:56 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.07962667847077837 --hypernet_embed=36 --hypernet_layers=1 --lr=0.0002014473656557767 --mixing_embed_dim=39
2022-07-15 12:26:01 INFO Running runs: ['ybb445su']
2022-07-15 12:26:11 INFO Cleaning up finished run: ybb445su
2022-07-15 12:26:12 INFO Agent received command: run
2022-07-15 12:26:12 INFO Agent starting run with config:
	epsilon_finish: 0.05358636792672278
	hypernet_embed: 26
	hypernet_layers: 2
	lr: 0.00016567883744157192
	mixing_embed_dim: 16
2022-07-15 12:26:12 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.05358636792672278 --hypernet_embed=26 --hypernet_layers=2 --lr=0.00016567883744157192 --mixing_embed_dim=16
2022-07-15 12:26:17 INFO Running runs: ['cutec69p']
2022-07-15 12:26:27 INFO Cleaning up finished run: cutec69p
2022-07-15 12:26:28 INFO Agent received command: run
2022-07-15 12:26:28 INFO Agent starting run with config:
	epsilon_finish: 0.031388537255921146
	hypernet_embed: 16
	hypernet_layers: 2
	lr: 0.0009318411996796424
	mixing_embed_dim: 42
2022-07-15 12:26:28 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.031388537255921146 --hypernet_embed=16 --hypernet_layers=2 --lr=0.0009318411996796424 --mixing_embed_dim=42
2022-07-15 12:26:33 INFO Running runs: ['kvwm2my0']
2022-07-15 12:27:55 INFO Running runs: []
2022-07-15 12:28:44 INFO Running runs: []
2022-07-15 12:28:44 INFO Agent received command: run
2022-07-15 12:28:44 INFO Agent starting run with config:
	epsilon_finish: 0.019931269479069584
	hypernet_embed: 43
	hypernet_layers: 2
	lr: 0.00019237018159229071
	mixing_embed_dim: 19
2022-07-15 12:28:44 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.019931269479069584 --hypernet_embed=43 --hypernet_layers=2 --lr=0.00019237018159229071 --mixing_embed_dim=19
2022-07-15 12:28:49 INFO Running runs: ['hlhcrdvo']
2022-07-15 12:29:00 INFO Cleaning up finished run: hlhcrdvo
2022-07-15 12:29:00 INFO Agent received command: run
2022-07-15 12:29:00 INFO Agent starting run with config:
	epsilon_finish: 0.06434237164289419
	hypernet_embed: 62
	hypernet_layers: 1
	lr: 0.000532270231300211
	mixing_embed_dim: 43
2022-07-15 12:29:00 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.06434237164289419 --hypernet_embed=62 --hypernet_layers=1 --lr=0.000532270231300211 --mixing_embed_dim=43
2022-07-15 13:27:35 INFO Running runs: []
2022-07-15 13:27:36 INFO Agent received command: run
2022-07-15 13:27:36 INFO Agent starting run with config:
	epsilon_finish: 0.09146776219234314
	hypernet_embed: 51
	hypernet_layers: 1
	lr: 0.0007958971180387078
	mixing_embed_dim: 62
2022-07-15 13:27:36 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.09146776219234314 --hypernet_embed=51 --hypernet_layers=1 --lr=0.0007958971180387078 --mixing_embed_dim=62
2022-07-15 13:27:41 INFO Running runs: ['b97zf3r7']
2022-07-15 13:35:27 INFO Running runs: []
2022-07-15 13:35:28 INFO Agent received command: run
2022-07-15 13:35:28 INFO Agent starting run with config:
	epsilon_finish: 0.05082098789083976
	hypernet_embed: 19
	hypernet_layers: 1
	lr: 0.0009748476205219044
	mixing_embed_dim: 44
2022-07-15 13:35:28 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.05082098789083976 --hypernet_embed=19 --hypernet_layers=1 --lr=0.0009748476205219044 --mixing_embed_dim=44
2022-07-15 13:35:33 INFO Running runs: ['4dnkxpw7']
2022-07-15 13:36:47 INFO Running runs: []
2022-07-15 13:36:48 INFO Agent received command: run
2022-07-15 13:36:48 INFO Agent starting run with config:
	epsilon_finish: 0.047166133532423014
	hypernet_embed: 24
	hypernet_layers: 1
	lr: 0.0004612643106347401
	mixing_embed_dim: 18
2022-07-15 13:36:48 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.047166133532423014 --hypernet_embed=24 --hypernet_layers=1 --lr=0.0004612643106347401 --mixing_embed_dim=18
2022-07-15 13:36:53 INFO Running runs: ['o4atlsxg']
2022-07-15 13:45:43 INFO Running runs: []
2022-07-15 13:45:44 INFO Agent received command: run
2022-07-15 13:45:44 INFO Agent starting run with config:
	epsilon_finish: 0.0643155175206163
	lr: 0.0009050754324373144
2022-07-15 13:45:44 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.0643155175206163 --lr=0.0009050754324373144
2022-07-15 13:45:49 INFO Running runs: ['gwva511c']
2022-07-15 13:45:59 INFO Cleaning up finished run: gwva511c
2022-07-15 13:46:02 INFO Agent received command: run
2022-07-15 13:46:02 INFO Agent starting run with config:
	epsilon_finish: 0.018066700233268763
	lr: 0.0005247664784903173
2022-07-15 13:46:02 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.018066700233268763 --lr=0.0005247664784903173
2022-07-15 13:46:07 INFO Running runs: ['i4qotygs']
2022-07-15 13:46:17 INFO Cleaning up finished run: i4qotygs
2022-07-15 13:46:17 INFO Agent received command: run
2022-07-15 13:46:17 INFO Agent starting run with config:
	epsilon_finish: 0.0922029266506648
	lr: 0.00013196883383513955
2022-07-15 13:46:17 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.0922029266506648 --lr=0.00013196883383513955
2022-07-15 13:46:22 INFO Running runs: ['9juvrdph']
2022-07-15 13:46:33 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2022-07-15 13:46:33 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2022-07-15 13:46:45 INFO Running runs: []
2022-07-15 13:46:46 INFO Agent received command: run
2022-07-15 13:46:46 INFO Agent starting run with config:
	epsilon_finish: 0.046651080885799986
	lr: 0.000931398887639625
2022-07-15 13:46:46 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.046651080885799986 --lr=0.000931398887639625
2022-07-15 13:46:51 INFO Running runs: ['q8rlqc36']
2022-07-15 13:47:01 INFO Cleaning up finished run: q8rlqc36
2022-07-15 13:47:02 INFO Agent received command: run
2022-07-15 13:47:02 INFO Agent starting run with config:
	epsilon_finish: 0.01196909131272524
	lr: 0.00016975912354690937
2022-07-15 13:47:02 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.01196909131272524 --lr=0.00016975912354690937
2022-07-15 13:47:07 INFO Running runs: ['tjkpqr5a']
2022-07-15 13:47:17 INFO Cleaning up finished run: tjkpqr5a
2022-07-15 13:47:18 INFO Agent received command: run
2022-07-15 13:47:18 INFO Agent starting run with config:
	epsilon_finish: 0.06173137643475541
	lr: 0.0001806834207894684
2022-07-15 13:47:18 INFO About to run command: /usr/bin/env python src/main.py --epsilon_finish=0.06173137643475541 --lr=0.0001806834207894684
2022-07-15 13:47:23 INFO Running runs: ['3z8ye12j']
2022-07-15 13:47:33 ERROR Detected 3 failed runs in the first 60 seconds, shutting down.
2022-07-15 13:47:33 INFO To disable this check set WANDB_AGENT_DISABLE_FLAPPING=true
2022-07-15 13:49:03 INFO Running runs: []
2022-07-15 13:49:04 INFO Agent received command: run
2022-07-15 13:49:04 INFO Agent starting run with config:
	lr: 0.00011065206108104349
2022-07-15 13:49:04 INFO About to run command: /usr/bin/env python src/main.py --lr=0.00011065206108104349
2022-07-15 13:49:09 INFO Running runs: ['m1fhfvki']
2022-07-15 13:49:19 INFO Cleaning up finished run: m1fhfvki
2022-07-15 13:49:20 INFO Agent received command: run
2022-07-15 13:49:20 INFO Agent starting run with config:
	lr: 0.00035922052403744136
2022-07-15 13:49:20 INFO About to run command: /usr/bin/env python src/main.py --lr=0.00035922052403744136
