/Users/jonnycook/Desktop/MARLGen/epymarl/src/main.py:87: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  if isinstance(v, collections.Mapping):
[INFO 13:30:11] root Saving to FileStorageObserver in results/sacred.
[DEBUG 13:30:11] pymarl Using capture mode "fd"
Seed: 5795
about to run
KWARGS
{'seed': 5795, 'level_seeds': array([3676, 2472, 6884, ..., 5061, 2692, 8383])}
KWARGS
{'seed': 5796, 'level_seeds': array([3676, 2472, 6884, ..., 5061, 2692, 8383])}
[2022-07-18 13:30:12.053] [info] No level specified, will use the first level described in the GDY.
[2022-07-18 13:30:12.063] [info] No level specified, will use the first level described in the GDY.
[INFO 13:30:11] pymarl Running command 'my_main'
[INFO 13:30:12] pymarl Started run with ID "150"
[DEBUG 13:30:12] pymarl Starting Heartbeat
[DEBUG 13:30:12] my_main Started
[WARNING 13:30:12] my_main CUDA flag use_cuda was switched OFF automatically because no CUDA devices are available!
[INFO 13:30:12] my_main Experiment Parameters:
[INFO 13:30:12] my_main
{   'action_selector': 'epsilon_greedy',
    'add_value_last_step': True,
    'agent': 'rnn',
    'agent_output_type': 'q',
    'batch_size': 10,
    'batch_size_run': 2,
    'buffer_cpu_only': True,
    'buffer_size': 5000,
    'checkpoint_path': '',
    'critic_type': 'ac_critic',
    'double_q': True,
    'entropy_coef': 0.01,
    'env': 'griddlygen',
    'env_args': {   'level_seeds': array([3676, 2472, 6884, ..., 5061, 2692, 8383]),
                    'seed': 5795},
    'epochs': 4,
    'eps_clip': 0.2,
    'epsilon_anneal_time': 5000,
    'epsilon_finish': 0.05,
    'epsilon_start': 1.0,
    'evaluate': False,
    'evaluation_epsilon': 0.0,
    'gamma': 0.99,
    'grad_norm_clip': 10,
    'hidden_dim': 64,
    'hypergroup': None,
    'hypernet_embed': 64,
    'hypernet_layers': 2,
    'label': 'default_label',
    'learner': 'q_learner',
    'learner_log_interval': 10000,
    'load_step': 0,
    'local_results_path': 'results',
    'log_interval': 10000,
    'lr': 0.0005,
    'mac': 'basic_mac',
    'mask_before_softmax': True,
    'max_before_softmax': True,
    'mixer': 'qmix',
    'mixing_embed_dim': 32,
    'name': 'qmix',
    'obs_agent_id': True,
    'obs_individual_obs': False,
    'obs_last_action': False,
    'optim_alpha': 0.99,
    'optim_eps': 1e-05,
    'q_nstep': 5,
    'repeat_id': 1,
    'runner': 'parallel',
    'runner_log_interval': 1000,
    'save_model': False,
    'save_model_interval': 50000,
    'save_replay': False,
    'seed': 5795,
    'standardise_returns': False,
    'standardise_rewards': True,
    't_max': 20050000,
    'target_update_interval_or_tau': 200,
    'test_greedy': True,
    'test_interval': 50000,
    'test_nepisode': 100,
    'use_cuda': False,
    'use_rnn': False,
    'use_tensorboard': False}
Process Process-2:
Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/runners/parallel_runner.py", line 260, in env_worker
    remote.send(env.get_env_info())
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/envs/game_2.py", line 282, in get_env_info
    "state_shape": self.get_state_size(),
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/envs/game_2.py", line 206, in get_state_size
    state_size = len(self.get_state().flatten())
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/envs/game_2.py", line 202, in get_state
    return super()._get_observation(self.game.observe(), self._global_observer_type)
RuntimeError: Observer not ready, must be initialized and reset before update() can be called.
Exception ignored in: <function VideoRecorder.__del__ at 0x7ffc0a81d050>
Traceback (most recent call last):
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/griddly/RenderTools.py", line 99, in __del__
    self.close()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/griddly/RenderTools.py", line 95, in close
    self._image_encoder.close()
AttributeError: 'VideoRecorder' object has no attribute '_image_encoder'
[DEBUG 13:30:44] pymarl Stopping Heartbeat
[WARNING 13:30:44] pymarl Aborted after 0:00:33!
Traceback (most recent call last):
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/main.py", line 147, in <module>
    ex.run_commandline(params)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/sacred/experiment.py", line 318, in run_commandline
    options=args,
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/sacred/experiment.py", line 276, in run
    run()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/sacred/run.py", line 238, in __call__
    self.result = self.main_function(*args)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/site-packages/sacred/config/captured_function.py", line 42, in captured_function
    result = wrapped(*args, **kwargs)
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/main.py", line 65, in my_main
    run(_run, config, _log)
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/run.py", line 56, in run
    run_sequential(args=args, logger=logger)
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/run.py", line 86, in run_sequential
    runner = r_REGISTRY[args.runner](args=args, logger=logger)
  File "/Users/jonnycook/Desktop/MARLGen/epymarl/src/runners/parallel_runner.py", line 36, in __init__
    self.env_info = self.parent_conns[0].recv()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/multiprocessing/connection.py", line 250, in recv
    buf = self._recv_bytes()
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/multiprocessing/connection.py", line 407, in _recv_bytes
    buf = self._recv(4)
  File "/Users/jonnycook/opt/anaconda3/envs/MARLGen/lib/python3.7/multiprocessing/connection.py", line 379, in _recv
    chunk = read(handle, remaining)
